name: uit_cantin
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluro: "^1.3.1"
  diagonal: ^1.0.1
  image_picker: ^0.4.10
  http: ^0.12.0+1
  shared_preferences: ^0.4.0
  carousel_pro: ^0.0.13
  flutter_rating: ^0.0.2
  flutter_slidable: ^0.5.3
  barcode_scan: ^0.0.4
  qr_flutter: ^1.1.5
  gradient_app_bar: ^0.1.3
  shimmer: ^1.0.0
  flutter_money_formatter: ^0.8.3
  flutter_speed_dial: ^1.2.1
  extended_navbar_scaffold: ^1.0.1
  flutter_multi_carousel: ^1.0.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/login.jpg
    - assets/uit1.jpg
    - assets/notification.png
    - assets/user.png
    - assets/fork.png
    - assets/rice.jpg
    - assets/background1.png
    - assets/background2.png
    - assets/cutlery.png
    - assets/sale.png
    - assets/bar.jpg
    - assets/avatar.png
    - assets/call-center.png
    - assets/online-menu.png
    - assets/order-success.png
    - assets/fitness_app/
    - assets/atm.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed/RobotoCondensed-Bold.ttf
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
